name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: false

      - name: Run tests
        run: uv run pytest -sv

      - name: Run Ruff check
        run: uvx ruff check .

      - name: Run Ruff format
        run: uvx ruff format --check .

      - name: Run ty
        run: uvx ty check .
